INSERT INTO [dbo].[EditBook] (EditName) 
VALUES
    ('Acantilado'),
    ('Adeshoras'),
    ('Alba Editorial'),
    ('Alianza Editorial'),
    ('Almadía'),
    ('Alrevés Editorial'),
    ('Alfaguara'),
    ('Alma'),
    ('Anagrama'),
    ('Arpa Editores'),
    ('Astiberri'),
    ('Austral'),
    ('Baile del Sol'),
    ('Bartleby Editores'),
    ('Blackie Books'),
    ('Booket'),
    ('Cátedra'),
    ('Capitán Swing'),
    ('DeBolsillo'),
    ('Debate'),
    ('Destino'),
    ('Editorial Anaya'),
    ('Editorial Ariel'),
    ('Editorial Atalanta'),
    ('Editorial Comanegra'),
    ('Editorial Comares'),
    ('Editorial Funambulista'),
    ('Editorial Gredos'),
    ('Editorial Hiperión'),
    ('Editorial Huso'),
    ('Editorial Minerva'),
    ('Editorial Obelisco'),
    ('Editorial Periférica'),
    ('Editorial Pre-Textos'),
    ('Editorial Páginas Libres'),
    ('Editorial Renacimiento'),
    ('Editorial Sirio'),
    ('Editorial Trotta'),
    ('Editorial Trifaldi'),
    ('Ediciones Atlantis'),
    ('Ediciones B'),
    ('Ediciones Cátedra'),
    ('Ediciones Casiopea'),
    ('Ediciones El Transbordador'),
    ('Ediciones Encuentro'),
    ('Ediciones La Cúpula'),
    ('Ediciones Menguantes'),
    ('Ediciones Siruela'),
    ('Ediciones del Oriente y del Mediterráneo'),
    ('Ediciones del Viento'),
    ('El Aleph Editores'),
    ('El Desvelo Ediciones'),
    ('Eterna Cadencia'),
    ('Espasa'),
    ('Errata Naturae'),
    ('Fórcola Ediciones'),
    ('Fulgencio Pimentel'),
    ('Galaxia Gutenberg'),
    ('Gallo Nero Ediciones'),
    ('Herder Editorial'),
    ('Hermida Editores'),
    ('Hoja de Lata'),
    ('Huerga y Fierro Editores'),
    ('Impedimenta'),
    ('La Esfera de los Libros'),
    ('La Fábrica Editorial'),
    ('La Oficina Ediciones'),
    ('Lengua de Trapo'),
    ('Libros de la Ballena'),
    ('Libros del Asteroide'),
    ('Libros del Innombrable'),
    ('Libros del Zorro Rojo'),
    ('Maeva Ediciones'),
    ('Malpaso Ediciones'),
    ('Minúscula'),
    ('Nórdica Libros'),
    ('Páginas de Espuma'),
    ('Pepitas de Calabaza'),
    ('Periférica'),
    ('Planeta'),
    ('Plaza Janés'),
    ('Plutón'),
    ('Páginas Libres'),
    ('Random House Mondadori'),
    ('Rey Naranjo Editores'),
    ('Roca Editorial'),
    ('Sajalín Editores'),
    ('Salamandra'),
    ('Santillana'),
    ('Seix Barral'),
    ('Sexto Piso'),
    ('Siruela'),
    ('Siete Pisos Editorial'),
    ('Tres Hermanas'),
    ('Turner'),
    ('Tusquets Editores'),
    ('UOC'),
    ('Visor Libros');
